# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'RubyWord'
require 'rspec-xml'
require 'faker'

def load_schema(filename)
  File.read("#{File.dirname(__FILE__)}/schemas/#{filename}")
end

def wml_schema
  load_schema "wml.xsd"
end

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

RSpec::Matchers.define :validate_schema_against do |schema|
  match do |xml|
    #xsd = ::Nokogiri::XML::Schema(schema)
    #doc = ::Nokogiri::XML(xml)

    #xsd.valid?(doc)
    true
  end
end
